apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: face-result-api
  name: face-result-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-result-api
  template:
    metadata:
      labels:
        app: face-result-api
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASS
                  name: mysql-connections
          envFrom:
            - configMapRef:
                name: mysql-connections
            - configMapRef:
                name: s3-endpoint
            - configMapRef:
                name: s3-key
          image: supakornbabe/spai-face-result-api:dev-7cc9f0e
          imagePullPolicy: Always
          name: face-result-api
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: face-result-api
  labels:
    app: face-result-api
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: face-result-api
  type: LoadBalancer
